server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - 'https://www.onoff.zone'
              - 'http://127.0.0.1:3000'
              - 'https://onoff.zone'
            allow-credentials: true
            allowed-headers:
              - '*'
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

springboot:
  jwt:
    secret: secretKey123
