spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.124.192.129:3306/PRODUCTS?createDatabaseIfNotExist=true
#    url: jdbc:mariadb://maria:3306/products?createDatabaseIfNotExist=true?
#    url: jdbc:mariadb://3.37.91.99:3306/products?createDatabaseIfNotExist=true
    username: root
    password: qwer1234
  application:
    name: Product-Service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
#  data:
#    web:
#      pageable:
#        default-page-size: 2


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true



#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

server:
  port: 12000

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: 13.124.192.129

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://onoff-eureka.kro.kr:8761/eureka