
# default
spring:
    profiles:
      active: dev
    application:
      name: User-Service
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    ## spring jpa hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${MY_DATA_SOURCE}
    username: ${MY_DATA_USERNAME}
    password: ${MY_DATA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

# 서버 실행 포트
server:
  port: ${MY_INSTANCE_PORT}

# eureka
eureka:
  instance:
    instance-id: ${MY_EUREKA_CLIENT_HOST_IP}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: ${MY_EUREKA_CLIENT_HOST_IP}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${MY_EUREKA_CLIENT_DEFAULT_ZONE}

# oauth
oauth:
  kakao:
    oauth_uri : ${MY_OAUTH_KAKAO_OAUTH_URI}
    data_uri : ${MY_OAUTH_KAKAO_DATA_URI}
    grant_type : ${MY_OAUTH_KAKAO_GRANT_TYPE}
    client_id : ${MY_OAUTH_KAKAO_CLIENT_ID}
    redirect_uri_signup : ${MY_OAUTH_KAKAO_REDIRECT_URI_SIGNUP}
    redirect_uri_signin : ${MY_OAUTH_KAKAO_REDIRECT_URI_SIGNIN}
    client_secret : ${MY_OAUTH_KAKAO_CLIENT_SECRET}
springboot:
  jwt:
    secret: ${MY_JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    ## spring jpa hibernate
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${MY_DATA_SOURCE}
    username: ${MY_DATA_USERNAME}
    password: ${MY_DATA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

# 서버 실행 포트
server:
  port: ${MY_INSTANCE_PORT}

# eureka
eureka:
  instance:
    instance-id: ${MY_EUREKA_CLIENT_HOST_IP}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: ${MY_EUREKA_CLIENT_HOST_IP}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${MY_EUREKA_CLIENT_DEFAULT_ZONE}

# oauth
oauth:
  kakao:
    oauth_uri : ${MY_OAUTH_KAKAO_OAUTH_URI}
    data_uri : ${MY_OAUTH_KAKAO_DATA_URI}
    grant_type : ${MY_OAUTH_KAKAO_GRANT_TYPE}
    client_id : ${MY_OAUTH_KAKAO_CLIENT_ID}
    redirect_uri_signup : ${MY_OAUTH_KAKAO_REDIRECT_URI_SIGNUP}
    redirect_uri_signin : ${MY_OAUTH_KAKAO_REDIRECT_URI_SIGNIN}
    client_secret : ${MY_OAUTH_KAKAO_CLIENT_SECRET}
springboot:
  jwt:
    secret: ${MY_JWT_SECRET}